// <auto-generated />
namespace hw4_ef_core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class UserProjectConnection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserProjectConnection));
        
        string IMigrationMetadata.Id
        {
            get { return "202411210517241_UserProjectConnection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
